# NLP Exercises

We have five exercises in this section. The exercises are:
1. Build your own tokenizer, where you need to implement two functions to implement a tokenizer based on regular expression.
2. Get tags from Trump speech.
3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.
4. Build your own Bag Of Words implementation using tokenizer created before.
5. Build a 5-gram model and clean up the results.

## Exercise 1. Build your own tokenizer

Build two different tokenizers:
- ``tokenize_sentence``: function tokenizing text into sentences,
- ``tokenize_word``: function tokenizing text into words.

In [5]:
import re
from typing import List

def tokenize_words(text: str) -> list:
    """Tokenize text into words using regex.

    Parameters
    ----------
    text: str
            Text to be tokenized

    Returns
    -------
    List[str]
            List containing words tokenized from text

    """
    pattern = "\\s+"
    words = re.split(pattern, text)
    return words

def tokenize_sentence(text: str) -> list:
    """Tokenize text into words using regex.

    Parameters
    ----------
    text: str
            Text to be tokenized

    Returns
    -------
    List[str]
            List containing words tokenized from text

    """
    pattern = "(?<=[.!?]) +"
    sentences = re.split(pattern, text)
    return sentences

text = "Here we go again. I was supposed to add this text later.\
Well, it's 10.p.m. here, and I'm actually having fun making this course. :o\
I hope you are getting along fine with this presentation, I really did try.\
And one last sentence, just so you can test you tokenizers better."

print("Tokenized sentences:")
print(tokenize_sentence(text))

print("Tokenized words:")
print(tokenize_words(text))

Tokenized sentences:
['Here we go again.', "I was supposed to add this text later.Well, it's 10.p.m.", "here, and I'm actually having fun making this course.", ':oI hope you are getting along fine with this presentation, I really did try.And one last sentence, just so you can test you tokenizers better.']
Tokenized words:
['Here', 'we', 'go', 'again.', 'I', 'was', 'supposed', 'to', 'add', 'this', 'text', 'later.Well,', "it's", '10.p.m.', 'here,', 'and', "I'm", 'actually', 'having', 'fun', 'making', 'this', 'course.', ':oI', 'hope', 'you', 'are', 'getting', 'along', 'fine', 'with', 'this', 'presentation,', 'I', 'really', 'did', 'try.And', 'one', 'last', 'sentence,', 'just', 'so', 'you', 'can', 'test', 'you', 'tokenizers', 'better.']


## Exercise 2. Get tags from Trump speech using NLTK

You should use the ``trump.txt`` file, read it and find the tags for each word. Use NLTK for it.

In [16]:
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')
file = open("../datasets/trump.txt", "r",encoding="utf-8") 
trump = file.read()
words = word_tokenize(trump)

print(words)
# fill the gap and imports

['Thank', 'you', 'very', 'much', '.', 'Mr.', 'Speaker', ',', 'Mr.', 'Vice', 'President', ',', 'Members', 'of', 'Congress', ',', 'the', 'First', 'Lady', 'of', 'the', 'United', 'States', ',', 'and', 'citizens', 'of', 'America', ':', 'Tonight', ',', 'as', 'we', 'mark', 'the', 'conclusion', 'of', 'our', 'celebration', 'of', 'Black', 'History', 'Month', ',', 'we', 'are', 'reminded', 'of', 'our', 'Nation', "'s", 'path', 'towards', 'civil', 'rights', 'and', 'the', 'work', 'that', 'still', 'remains', 'to', 'be', 'done', '.', 'Recent', 'threats', 'targeting', 'Jewish', 'community', 'centers', 'and', 'vandalism', 'of', 'Jewish', 'cemeteries', ',', 'as', 'well', 'as', 'last', 'week', "'s", 'shooting', 'in', 'Kansas', 'City', ',', 'remind', 'us', 'that', 'while', 'we', 'may', 'be', 'a', 'nation', 'divided', 'on', 'policies', ',', 'we', 'are', 'a', 'country', 'that', 'stands', 'united', 'in', 'condemning', 'hate', 'and', 'evil', 'in', 'all', 'of', 'its', 'very', 'ugly', 'forms', '.', 'Each', 'Ameri

[nltk_data] Downloading package punkt to /home/crdds/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


## Exercise 3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.

Please use Python list features to get the last 10 sentences and display nouns from it.

In [34]:
import spacy

file = open("../datasets/trump.txt", "r",encoding='utf-8') 
trump = file.read() 


nlp = spacy.load("en_core_web_sm")
doc = nlp(trump)

my_list = list(doc.sents)

ans = []

for span in my_list:
    for i in range(span.start, span.end):
        token = doc[i]
        if token.pos_ == "NOUN":
            ans.append(token.text)
            
print (ans)
### here comes your code


['Members', 'citizens', 'Tonight', 'conclusion', 'celebration', 'Nation', 'path', 'rights', 'work', 'threats', 'community', 'centers', 'vandalism', 'cemeteries', 'week', 'shooting', 'nation', 'policies', 'country', 'hate', 'evil', 'forms', 'generation', 'torch', 'truth', 'liberty', 'justice', 'chain', 'way', 'present', 'torch', 'hands', 'world', 'tonight', 'message', 'unity', 'strength', 'message', 'heart', 'chapter', 'greatness', 'pride', 'Nation', 'surge', 'optimism', 'dreams', 'grasp', 'today', 'renewal', 'spirit', 'allies', 'nations', 'world', 'friend', 'foe', 'years', 'anniversary', 'founding', 'years', 'day', 'independence', 'milestones', 'history', 'world', 'year', 'kind', 'country', 'children', 'mistakes', 'decades', 'course', 'future', 'class', 'shrink', 'jobs', 'wealth', 'countries', 'project', 'fates', 'children', 'cities', 'places', 'land', 'borders', 'nations', 'borders', 'drugs', 'rate', 'trillions', 'trillions', 'dollars', 'infrastructure', 'home', 'feet', 'rebellion', '

## Exercise 4. Build your own Bag Of Words implementation using tokenizer created before 

You need to implement following methods:

- ``fit_transform`` - gets a list of strings and returns matrix with it's BoW representation
- ``get_features_names`` - returns list of words corresponding to columns in BoW

In [74]:
import numpy as np
import spacy

class BagOfWords:
    """Basic BoW implementation."""
    
    __nlp = spacy.load("en_core_web_sm")
    __bow_list = []
    
    # your code goes maybe also here    
    
    def fit_transform(self, corpus: list):
        """Transform list of strings into BoW array.

        Parameters
        ----------
        corpus: List[str]
                Corpus of texts to be transforrmed

        Returns
        -------
        np.array
                Matrix representation of BoW

        """
        d = len(corpus)
        dic = {}
        for count, doc in enumerate(corpus):
            tokens = self.__nlp(doc)
            for token in tokens:
                if token.is_alpha:
                    if token.text not in dic:
                        dic[token.text] = [0]*d
                    dic[token.text][count] =+ 1
                    
        
        matrix = []
        
        for i in sorted(dic.items()):
            self.__bow_list.append(i[0])
            matrix.append(i[1])
           
        return np.array(matrix).transpose()
        # your code goes here        
       
      

    def get_feature_names(self) -> list:
        """Return words corresponding to columns of matrix.

        Returns
        -------
        List[str]
                Words being transformed by fit function

        """   
        # your code goes here
        return self.__bow_list

corpus = [
     'Bag Of Words is based on counting',
     'words occurences throughout multiple documents.',
     'This is the third document.',
     'As you can see most of the words occur only once.',
     'This gives us a pretty sparse matrix, see below. Really, see below',
]    
    
vectorizer = BagOfWords()

X = vectorizer.fit_transform(corpus)
print(X)

vectorizer.get_feature_names()
len(vectorizer.get_feature_names())

[[0 1 1 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 0 0 1 1]
 [0 0 0 1 1 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0]]


33

## Exercise 5. Build a 5-gram model and clean up the results.

There are three tasks to do:
1. Use 5-gram model instead of 3.
2. Change to capital letter each first letter of a sentence.
3. Remove the whitespace between the last word in a sentence and . ! or ?.

Hint: for 2. and 3. implement a function called ``clean_generated()`` that takes the generated text and fix both issues at once. It could be easier to fix the text after it's generated rather then doing some changes in the while loop.

In [166]:
from nltk.book import *

wall_street = text7.tokens

import re

tokens = wall_street

def cleanup():
    compiled_pattern = re.compile("^[a-zA-Z0-9.!?]")
    clean = list(filter(compiled_pattern.match,tokens))
    return clean
tokens = cleanup()

def build_ngrams():
    ngrams = []
    for i in range(len(tokens)-N+1):
        ngrams.append(tokens[i:i+N])
    return ngrams

def ngram_freqs(ngrams):
    counts = {}

    for ngram in ngrams:
        token_seq  = SEP.join(ngram[:-1])
        last_token = ngram[-1]

        if token_seq not in counts:
            counts[token_seq] = {}

        if last_token not in counts[token_seq]:
            counts[token_seq][last_token] = 0

        counts[token_seq][last_token] += 1;

    return counts

def next_word(text, N, counts):

    token_seq = SEP.join(text.split()[-(N-1):]);
    choices = counts[token_seq].items();

    total = sum(weight for choice, weight in choices)
    r = random.uniform(0, total)
    upto = 0
    for choice, weight in choices:
        upto += weight;
        if upto > r: return choice
    assert False # should not reach here

In [172]:
def clean_generated(text):
    pattern = "(?<=[.!?]) +"
    my_list = re.split(pattern, text)
    new_text = ""
    for sen in my_list:
        if sen[-2:-1] == " ":
            new_text = new_text + sen[0:-2]+sen[-1]+" "
        else:
            new_text = new_text + sen +" "
        
    return new_text[0].capitalize() + new_text[1:-1]
    

import random # zapomniał Pan o imporcie :)

N=3 # fix it for other value of N

# Niestety nie mogłem przetestować dla N=5 ponieważ wykracza to poza IOPub data rate. 
# Używałem jupytera na zewnętrznym serwerze i nie mam nistety możliwości zrestatować notebooków z nowym data ratem. 

SEP=" "

sentence_count=5

ngrams = build_ngrams()
start_seq="We have"


counts = ngram_freqs(ngrams)

if start_seq is None: start_seq = random.choice(list(counts.keys()))
generated = start_seq.lower();

sentences = 0
while sentences < sentence_count:
    generated += SEP + next_word(generated, N, counts)
    sentences += 1 if generated.endswith(('.','!', '?')) else 0

# put your code here:

print(clean_generated(generated))

We have to use the aid effectively. The dispute has hampered the stock market gyrations than the futures industry is able to teach much longer. Mrs. Ward. Soon T-shirts appeared in the many appropriations bills now moving through Congress.
